package handler

import (
	"backend/pkg/common"
	"backend/services/storaged/entity"
	"backend/services/storaged/presenter"
	"encoding/csv"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strconv"
	"strings"
	"time"
)

// Interface to avoid circular imports
type CompanyUsecase interface {
	CreateCompany(company *entity.Company) (string, error)
	GetCompanyByID(id string) (*entity.Company, error)
	GetCompanyByEmail(email string) (*entity.Company, error)
	UpdateCompany(company *entity.Company) error
	AssignCompanyToOfficer(companyID, officerID, assignedBy string) error
	GetCompaniesByOfficerID(officerID string) ([]*entity.Company, error)
	GetAllCompanies() ([]*entity.Company, error)
	ImportCompaniesFromCSV(companies []*entity.Company) ([]string, error)
	UpdateApprovalStatus(companyID, status, notes string, updatedBy string) error
}

func getCompanyHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusOK)
	w.Write([]byte("success"))
}

func createCompany(service CompanyUsecase) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}

		var req presenter.CompanyRequest
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			http.Error(w, fmt.Sprintf("unable to decode request body, err=%v", err), http.StatusBadRequest)
			return
		}

		// Convert presenter request to entity
		hrData := entity.HR{
			Name:        req.HR.Name,
			Email:       req.HR.Email,
			Phone:       req.HR.Phone,
			Position:    req.HR.Position,
			LinkedInURL: req.HR.LinkedInURL,
		}

		companyDetailsData := entity.CompanyDetails{
			Website:     req.CompanyDetails.Website,
			Industry:    req.CompanyDetails.Industry,
			FoundedYear: req.CompanyDetails.FoundedYear,
			Size:        req.CompanyDetails.Size,
			Description: req.CompanyDetails.Description,
			Logo:        req.CompanyDetails.Logo,
		}

		driveDetailsData := entity.DriveDetails{
			Status:           entity.DriveStatus(req.DriveDetails.Status),
			ScheduledDate:    req.DriveDetails.ScheduledDate,
			NumberOfOffers:   req.DriveDetails.NumberOfOffers,
			NumberHired:      req.DriveDetails.NumberHired,
			RolesOffered:     req.DriveDetails.RolesOffered,
			MinCGPA:          req.DriveDetails.MinCGPA,
			EligibleBranches: req.DriveDetails.EligibleBranches,
			Notes:            req.DriveDetails.Notes,
		}

		company, err := entity.NewCompany(
			0, // ID will be generated by repository
			req.CompanyName,
			req.LastContacted,
			req.FollowUp,
			req.Remarks,
			req.TargetBranch,
			req.Packages,
			hrData,
			driveDetailsData,
			companyDetailsData,
			req.Approved,
			req.IsValidation,
			req.Location,
		)
		if err != nil {
			http.Error(w, fmt.Sprintf("unable to create company entity, err=%v", err), http.StatusBadRequest)
			return
		}

		// Set creator
		company.CreatedBy = req.CreatedBy

		companyID, err := service.CreateCompany(company)
		if err != nil {
			http.Error(w, fmt.Sprintf("unable to create company, err=%v", err), http.StatusInternalServerError)
			return
		}

		// Create a response
		response := presenter.CompanyResponse{
			ID:             companyID,
			CompanyName:    company.CompanyName,
			LastContacted:  company.LastContacted,
			FollowUp:       company.FollowUp,
			Packages:       company.Packages,
			Remarks:        company.Remarks,
			HR:             req.HR,
			TargetBranch:   company.TargetBranch,
			IsValidation:   company.IsValidation,
			Approved:       company.Approved,
			DriveDetails:   req.DriveDetails,
			CompanyDetails: req.CompanyDetails,
			Location:       company.Location,
			CreatedAt:      company.CreatedAt,
		}

		w.WriteHeader(http.StatusOK)
		if err := json.NewEncoder(w).Encode(response); err != nil {
			http.Error(w, fmt.Sprintf("unable to encode to JSON, err=%v", err), http.StatusInternalServerError)
			return
		}
	}
}

func getCompanyByID(service CompanyUsecase) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}

		// Extract ID from path /v1/company/id/{id}
		path := strings.TrimPrefix(r.URL.Path, "/v1/company/id/")
		if path == "" {
			http.Error(w, "id is required", http.StatusBadRequest)
			return
		}

		// Remove any trailing slashes and get the ID
		id := strings.TrimSuffix(path, "/")
		if id == "" {
			http.Error(w, "id is required", http.StatusBadRequest)
			return
		}

		company, err := service.GetCompanyByID(id)
		if err != nil {
			http.Error(w, fmt.Sprintf("unable to get company by id, err=%v", err), http.StatusInternalServerError)
			return
		}

		response := companyToResponse(company)

		w.WriteHeader(http.StatusOK)
		if err := json.NewEncoder(w).Encode(response); err != nil {
			http.Error(w, fmt.Sprintf("unable to encode to JSON, err=%v", err), http.StatusInternalServerError)
			return
		}
	}
}

func getCompanyByEmail(service CompanyUsecase) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}

		// Extract email from path /v1/company/email/{email}
		path := strings.TrimPrefix(r.URL.Path, "/v1/company/email/")
		if path == "" {
			http.Error(w, "email is required", http.StatusBadRequest)
			return
		}

		// Remove any trailing slashes and get the email
		email := strings.TrimSuffix(path, "/")
		if email == "" {
			http.Error(w, "email is required", http.StatusBadRequest)
			return
		}

		company, err := service.GetCompanyByEmail(email)
		if err != nil {
			http.Error(w, fmt.Sprintf("unable to get company by email, err=%v", err), http.StatusInternalServerError)
			return
		}

		response := companyToResponse(company)

		w.WriteHeader(http.StatusOK)
		if err := json.NewEncoder(w).Encode(response); err != nil {
			http.Error(w, fmt.Sprintf("unable to encode to JSON, err=%v", err), http.StatusInternalServerError)
			return
		}
	}
}

func updateCompany(service CompanyUsecase) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPut {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}

		var req presenter.CompanyUpdateRequest
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			http.Error(w, fmt.Sprintf("unable to decode request body, err=%v", err), http.StatusBadRequest)
			return
		}

		// Get existing company
		company, err := service.GetCompanyByID(req.ID)
		if err != nil {
			http.Error(w, fmt.Sprintf("unable to get company, err=%v", err), http.StatusInternalServerError)
			return
		}

		// Update company details
		if req.CompanyName != "" {
			company.CompanyName = req.CompanyName
		}
		if req.LastContacted {
			company.LastContacted = true
		}
		if !req.FollowUp.IsZero() {
			company.FollowUp = req.FollowUp
		}
		if req.Remarks != "" {
			company.Remarks = req.Remarks
		}
		if req.TargetBranch != "" {
			company.TargetBranch = req.TargetBranch
		}
		if req.Location != "" {
			company.Location = req.Location
		}
		if len(req.Packages) > 0 {
			company.Packages = req.Packages
		}

		// Update HR details if provided
		if req.HR.Name != "" || req.HR.Email != "" || req.HR.Phone != "" {
			if req.HR.Name != "" {
				company.HR.Name = req.HR.Name
			}
			if req.HR.Email != "" {
				company.HR.Email = req.HR.Email
			}
			if req.HR.Phone != "" {
				company.HR.Phone = req.HR.Phone
			}
			if req.HR.Position != "" {
				company.HR.Position = req.HR.Position
			}
			if req.HR.LinkedInURL != "" {
				company.HR.LinkedInURL = req.HR.LinkedInURL
			}
		}

		// Update Company Details if provided
		if req.CompanyDetails.Website != "" || req.CompanyDetails.Industry != "" {
			if req.CompanyDetails.Website != "" {
				company.CompanyDetails.Website = req.CompanyDetails.Website
			}
			if req.CompanyDetails.Industry != "" {
				company.CompanyDetails.Industry = req.CompanyDetails.Industry
			}
			if req.CompanyDetails.FoundedYear > 0 {
				company.CompanyDetails.FoundedYear = req.CompanyDetails.FoundedYear
			}
			if req.CompanyDetails.Size != "" {
				company.CompanyDetails.Size = req.CompanyDetails.Size
			}
			if req.CompanyDetails.Description != "" {
				company.CompanyDetails.Description = req.CompanyDetails.Description
			}
			if req.CompanyDetails.Logo != "" {
				company.CompanyDetails.Logo = req.CompanyDetails.Logo
			}
		}

		// Update Drive Details if provided
		if req.DriveDetails.Status != "" {
			company.DriveDetails.Status = entity.DriveStatus(req.DriveDetails.Status)

			// Only update these fields if we're updating the drive status
			if !req.DriveDetails.ScheduledDate.IsZero() {
				company.DriveDetails.ScheduledDate = req.DriveDetails.ScheduledDate
			}
			if req.DriveDetails.NumberOfOffers > 0 {
				company.DriveDetails.NumberOfOffers = req.DriveDetails.NumberOfOffers
			}
			if req.DriveDetails.NumberHired > 0 {
				company.DriveDetails.NumberHired = req.DriveDetails.NumberHired
			}
			if len(req.DriveDetails.RolesOffered) > 0 {
				company.DriveDetails.RolesOffered = req.DriveDetails.RolesOffered
			}
			if req.DriveDetails.MinCGPA > 0 {
				company.DriveDetails.MinCGPA = req.DriveDetails.MinCGPA
			}
			if len(req.DriveDetails.EligibleBranches) > 0 {
				company.DriveDetails.EligibleBranches = req.DriveDetails.EligibleBranches
			}
			if req.DriveDetails.Notes != "" {
				company.DriveDetails.Notes = req.DriveDetails.Notes
			}
		}

		// Set validation flag if requested
		if req.IsValidation {
			company.IsDataValidated = true
		}

		// Handle approval based on system settings
		if common.CurrentSettings.ApprovalMode == "auto" {
			company.ApprovalStatus = "APPROVED"
		} else {
			company.ApprovalStatus = "PENDING"
		}

		// Save updates
		err = service.UpdateCompany(company)
		if err != nil {
			http.Error(w, fmt.Sprintf("unable to update company, err=%v", err), http.StatusInternalServerError)
			return
		}

		response := companyToResponse(company)

		w.WriteHeader(http.StatusOK)
		if err := json.NewEncoder(w).Encode(response); err != nil {
			http.Error(w, fmt.Sprintf("unable to encode to JSON, err=%v", err), http.StatusInternalServerError)
			return
		}
	}
}

func assignCompanyToOfficer(service CompanyUsecase) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}

		var req presenter.AssignmentRequest
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			http.Error(w, fmt.Sprintf("unable to decode request body, err=%v", err), http.StatusBadRequest)
			return
		}

		err := service.AssignCompanyToOfficer(req.CompanyID, req.OfficerID, req.AssignedBy)
		if err != nil {
			http.Error(w, fmt.Sprintf("unable to assign company to officer, err=%v", err), http.StatusInternalServerError)
			return
		}

		response := map[string]string{
			"status":  "success",
			"message": "Company assigned successfully",
		}

		w.WriteHeader(http.StatusOK)
		if err := json.NewEncoder(w).Encode(response); err != nil {
			http.Error(w, fmt.Sprintf("unable to encode to JSON, err=%v", err), http.StatusInternalServerError)
			return
		}
	}
}

func getCompaniesByOfficer(service CompanyUsecase) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}

		// Extract officer ID from path /v1/company/officer/{id}
		path := strings.TrimPrefix(r.URL.Path, "/v1/company/officer/")
		if path == "" {
			http.Error(w, "officer id is required", http.StatusBadRequest)
			return
		}

		// Remove any trailing slashes and get the ID
		officerID := strings.TrimSuffix(path, "/")
		if officerID == "" {
			http.Error(w, "officer id is required", http.StatusBadRequest)
			return
		}

		companies, err := service.GetCompaniesByOfficerID(officerID)
		if err != nil {
			http.Error(w, fmt.Sprintf("unable to get companies for officer, err=%v", err), http.StatusInternalServerError)
			return
		}

		var response []presenter.CompanyResponse
		for _, company := range companies {
			response = append(response, companyToResponse(company))
		}

		w.WriteHeader(http.StatusOK)
		if err := json.NewEncoder(w).Encode(response); err != nil {
			http.Error(w, fmt.Sprintf("unable to encode to JSON, err=%v", err), http.StatusInternalServerError)
			return
		}
	}
}

func getAllCompanies(service CompanyUsecase) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}

		companies, err := service.GetAllCompanies()
		if err != nil {
			http.Error(w, fmt.Sprintf("unable to get companies, err=%v", err), http.StatusInternalServerError)
			return
		}

		var response []presenter.CompanyResponse
		for _, company := range companies {
			response = append(response, companyToResponse(company))
		}

		w.WriteHeader(http.StatusOK)
		if err := json.NewEncoder(w).Encode(response); err != nil {
			http.Error(w, fmt.Sprintf("unable to encode to JSON, err=%v", err), http.StatusInternalServerError)
			return
		}
	}
}

func importCompaniesFromCSV(service CompanyUsecase) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}

		// Limit file size to 10MB
		r.ParseMultipartForm(10 << 20)

		// Get file from request
		file, _, err := r.FormFile("csvFile")
		if err != nil {
			http.Error(w, fmt.Sprintf("unable to get file from request, err=%v", err), http.StatusBadRequest)
			return
		}
		defer file.Close()

		// Get creator ID from form
		creatorID := r.FormValue("creatorID")
		if creatorID == "" {
			http.Error(w, "creator ID is required", http.StatusBadRequest)
			return
		}

		// Parse CSV
		reader := csv.NewReader(file)

		// Read header
		header, err := reader.Read()
		if err != nil {
			http.Error(w, fmt.Sprintf("unable to read CSV header, err=%v", err), http.StatusBadRequest)
			return
		}

		// Map header columns to indices
		headerMap := make(map[string]int)
		for i, column := range header {
			headerMap[strings.TrimSpace(strings.ToLower(column))] = i
		}

		// Required columns
		requiredColumns := []string{"company_name", "location", "target_branch"}
		for _, col := range requiredColumns {
			if _, exists := headerMap[col]; !exists {
				http.Error(w, fmt.Sprintf("missing required column: %s", col), http.StatusBadRequest)
				return
			}
		}

		// Parse records
		var companies []*entity.Company
		for {
			record, err := reader.Read()
			if err == io.EOF {
				break
			}
			if err != nil {
				continue // Skip invalid records
			}

			// Create company entity from CSV record
			company := &entity.Company{
				CompanyName:    getValue(record, headerMap, "company_name"),
				Location:       getValue(record, headerMap, "location"),
				TargetBranch:   getValue(record, headerMap, "target_branch"),
				Remarks:        getValue(record, headerMap, "remarks"),
				CreatedBy:      creatorID,
				CreatedAt:      time.Now(),
				UpdatedAt:      time.Now(),
				ApprovalStatus: "PENDING",
			}

			// Parse packages if available
			if idx, exists := headerMap["packages"]; exists && idx < len(record) {
				packages := strings.Split(record[idx], ",")
				for _, p := range packages {
					p = strings.TrimSpace(p)
					if p != "" {
						if packageValue, err := strconv.ParseFloat(p, 32); err == nil {
							company.Packages = append(company.Packages, float32(packageValue))
						}
					}
				}
			}

			// Set HR data if available
			company.HR = entity.HR{
				Name:     getValue(record, headerMap, "hr_name"),
				Email:    getValue(record, headerMap, "hr_email"),
				Phone:    getValue(record, headerMap, "hr_phone"),
				Position: getValue(record, headerMap, "hr_position"),
			}

			// Set company details if available
			company.CompanyDetails = entity.CompanyDetails{
				Website:  getValue(record, headerMap, "website"),
				Industry: getValue(record, headerMap, "industry"),
			}

			// Add to list if basic validation passes
			if company.CompanyName != "" && company.Location != "" && company.TargetBranch != "" {
				companies = append(companies, company)
			}
		}

		// Import companies to database
		importedIDs, err := service.ImportCompaniesFromCSV(companies)
		if err != nil {
			http.Error(w, fmt.Sprintf("unable to import companies, err=%v", err), http.StatusInternalServerError)
			return
		}

		response := map[string]interface{}{
			"status":      "success",
			"message":     fmt.Sprintf("Imported %d companies", len(importedIDs)),
			"importedIDs": importedIDs,
		}

		w.WriteHeader(http.StatusOK)
		if err := json.NewEncoder(w).Encode(response); err != nil {
			http.Error(w, fmt.Sprintf("unable to encode to JSON, err=%v", err), http.StatusInternalServerError)
			return
		}
	}
}

func updateApprovalStatus(service CompanyUsecase) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}

		var req presenter.ApprovalRequest
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			http.Error(w, fmt.Sprintf("unable to decode request body, err=%v", err), http.StatusBadRequest)
			return
		}

		// Validate status
		if req.Status != "APPROVED" && req.Status != "REJECTED" {
			http.Error(w, "status must be either APPROVED or REJECTED", http.StatusBadRequest)
			return
		}

		err := service.UpdateApprovalStatus(req.CompanyID, req.Status, req.Notes, req.UpdatedBy)
		if err != nil {
			http.Error(w, fmt.Sprintf("unable to update approval status, err=%v", err), http.StatusInternalServerError)
			return
		}

		response := map[string]string{
			"status":  "success",
			"message": fmt.Sprintf("Approval status updated to %s", req.Status),
		}

		w.WriteHeader(http.StatusOK)
		if err := json.NewEncoder(w).Encode(response); err != nil {
			http.Error(w, fmt.Sprintf("unable to encode to JSON, err=%v", err), http.StatusInternalServerError)
			return
		}
	}
}

func updateSystemSettings(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}

	var req presenter.SystemSettingsRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, fmt.Sprintf("unable to decode request body, err=%v", err), http.StatusBadRequest)
		return
	}

	// Validate approval mode
	if req.ApprovalMode != "auto" && req.ApprovalMode != "manual" {
		http.Error(w, "approval mode must be either 'auto' or 'manual'", http.StatusBadRequest)
		return
	}

	// Update global settings
	common.CurrentSettings.ApprovalMode = req.ApprovalMode

	response := map[string]string{
		"status":       "success",
		"approvalMode": req.ApprovalMode,
	}

	w.WriteHeader(http.StatusOK)
	if err := json.NewEncoder(w).Encode(response); err != nil {
		http.Error(w, fmt.Sprintf("unable to encode to JSON, err=%v", err), http.StatusInternalServerError)
		return
	}
}

// Helper functions
func companyToResponse(company *entity.Company) presenter.CompanyResponse {
	return presenter.CompanyResponse{
		ID:            company.ID,
		CompanyName:   company.CompanyName,
		LastContacted: company.LastContacted,
		FollowUp:      company.FollowUp,
		Packages:      company.Packages,
		Remarks:       company.Remarks,
		HR: presenter.HRData{
			Name:        company.HR.Name,
			Email:       company.HR.Email,
			Phone:       company.HR.Phone,
			Position:    company.HR.Position,
			LinkedInURL: company.HR.LinkedInURL,
		},
		TargetBranch: company.TargetBranch,
		IsValidation: company.IsValidation,
		Approved:     company.Approved,
		DriveDetails: presenter.DriveDetailsData{
			Status:           string(company.DriveDetails.Status),
			ScheduledDate:    company.DriveDetails.ScheduledDate,
			NumberOfOffers:   company.DriveDetails.NumberOfOffers,
			NumberHired:      company.DriveDetails.NumberHired,
			RolesOffered:     company.DriveDetails.RolesOffered,
			MinCGPA:          company.DriveDetails.MinCGPA,
			EligibleBranches: company.DriveDetails.EligibleBranches,
			Notes:            company.DriveDetails.Notes,
		},
		CompanyDetails: presenter.CompanyDetailsData{
			Website:     company.CompanyDetails.Website,
			Industry:    company.CompanyDetails.Industry,
			FoundedYear: company.CompanyDetails.FoundedYear,
			Size:        company.CompanyDetails.Size,
			Description: company.CompanyDetails.Description,
			Logo:        company.CompanyDetails.Logo,
		},
		Location:        company.Location,
		AssignedTo:      company.AssignedTo,
		CreatedBy:       company.CreatedBy,
		CreatedAt:       company.CreatedAt,
		UpdatedAt:       company.UpdatedAt,
		IsDataValidated: company.IsDataValidated,
		ApprovalStatus:  company.ApprovalStatus,
		ApprovalNotes:   company.ApprovalNotes,
	}
}

func getValue(record []string, headerMap map[string]int, key string) string {
	if idx, exists := headerMap[key]; exists && idx < len(record) {
		return strings.TrimSpace(record[idx])
	}
	return ""
}

// RegisterCompanyHandlers registers all company-related handlers
func RegisterCompanyHandlers(service CompanyUsecase) {
	// Health check
	http.HandleFunc("/v1/company/health", getCompanyHealth)

	// Basic CRUD
	http.HandleFunc("/v1/company", createCompany(service))
	http.HandleFunc("/v1/company/update", updateCompany(service))
	http.HandleFunc("/v1/company/id/", getCompanyByID(service))
	http.HandleFunc("/v1/company/email/", getCompanyByEmail(service))

	// Assignment
	http.HandleFunc("/v1/company/assign", assignCompanyToOfficer(service))
	http.HandleFunc("/v1/company/officer/", getCompaniesByOfficer(service))

	// Import/Export
	http.HandleFunc("/v1/company/import", importCompaniesFromCSV(service))
	http.HandleFunc("/v1/company/all", getAllCompanies(service))

	// Approval
	http.HandleFunc("/v1/company/approve", updateApprovalStatus(service))

	// System settings
	http.HandleFunc("/v1/settings", updateSystemSettings)
}
